import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/navbar';
import AuthContext from '@/context/AuthContext';
import localFont from 'next/font/local';

// const inter = Inter({ subsets: ["latin"] });
const helvetica = localFont({
  src: '../../public/HelveticaNeue.otf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={helvetica.className}>
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
}
